version: '3'
services:
  win1:
    image: mcr.microsoft.com/windows/servercore:20H2-KB5008212
    container_name: far-container
    volumes:
      - "C:\\Program Files\\Far Manager:C:\\Program Files\\Far Manager"
    command: ["C:\\Program Files\\Far Manager\\Far.exe"]